version: '3.9'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: db

    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/posgressql

  # localstack:
  #   image: localstack/localstack:latest
  #   environment: 
  #     - AWS_DEFAULT_REGION=us-east-1
  #     - EDGE_PORT=4566
  #     - SERVICES=s3
  #   ports: 
  #     - '4566-4583:4566-4583'
  #   volumes: 
  #     - "${TEMPDIR:-/tmp/localstack}:/tmp/localstack"
  #     - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  db:
