name: Build Next App

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: npm i
      - run: npm run build
        env:
          DATABASE_URL: ''
          NEXTAUTH_SECRET: ''
          NEXTAUTH_URL: ''
          GOOGLE_CLIENT_ID: ''
          GOOGLE_CLIENT_SECRET: ''
